# Use the NGINX base image
FROM nginx:latest

# Copy the static files to the NGINX web root directory
COPY getform.html /usr/share/nginx/html/
COPY getDataTable.js /usr/share/nginx/html/

# Expose port 80 to allow incoming connections
EXPOSE 9000

# Start NGINX server when the container is launched
CMD ["nginx", "-g", "daemon off;"]
